export const segment = [
    "Ice Cream",
    "Ice Cubes",
    "Mushroom",
    "Incubation room",
    "Frozen Foods",
    "Dairy Products",
    "Banana Ripening Room",
    "Bakery and Confectionery",
    "Research Labs",
    "Chemicals",
    "Pharmaceuticals",
    "Agricultural",
    "Fruits and Vegetables",
    "Dry Fruits",
    "Meat and chicken",
    "Others",
];
